demo:
  advice-api-endpoint: https://api.adviceslip.com/advice/search/
  cache:
    enabled: false
    time-unit: MINUTES
    duration: 5

spring:
  cache:
    type: none

server:
  #servlet:
  #  context-path: /api
  port: 8080